//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace rokumoto {
namespace vending_machine {
namespace ev {

// コインの投入
struct Deposit {
    int money;	// 投入金額

};


// 購入
struct Buy {
    int slot;	// 購入番号

};


struct Refund {};	// 返金


struct Update {};


// 商品情報
struct ProductInfo {
    string_type name;	// 商品名
    int price;	// 価格
    int stock;	// 在庫数

};

} // namespace ev
} // namespace vending_machine
} // namespace rokumoto
} // namespace app
