//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace rokumoto {
namespace vending_machine {
namespace ev {
} // namespace ev
} // namespace vending_machine
} // namespace rokumoto
} // namespace app
