//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace rokumoto {
namespace vending_machine {
namespace ft {
using StateLog = app::StateLog;
} // namespace ft

namespace stub {
} // namespace stub

} // namespace vending_machine
} // namespace rokumoto
} // namespace app
