//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace rokumoto {
namespace vending_machine {
namespace ft {
struct Deposit;
struct DispensingSlot;
struct Slot;
struct Slots;
struct SlotUI;

//--------------------------------------
// Deposit interface
// 入金管理
//--------------------------------------
struct Deposit {
    virtual ~Deposit() = default;

    virtual bool is_ready(const ev::Deposit& e) const = 0;	// 金額投入済み？
    virtual bool has_deposit(int money = 1) const = 0;	// 投入金額チェック
    virtual void buy(int price = 0) = 0;	// 購入処理
    virtual void refund() = 0;	// 返金処理
    virtual void deposit(const ev::Deposit& e) = 0;	// コイン投入
};


//--------------------------------------
// DispensingSlot interface
// 商品取り出し口
//--------------------------------------
struct DispensingSlot {
    virtual ~DispensingSlot() = default;

    virtual void dispense(string_type name) = 0;	// 出力
};


//--------------------------------------
// Slot interface
// 商品スロット
//--------------------------------------
struct Slot {
    virtual ~Slot() = default;

    virtual bool has_deposit(const ft::Deposit& f0) const = 0;	// 入金は足りてる？
    virtual bool has_stock() const = 0;	// 在庫はある？
    virtual void buy(ft::Deposit& f0, ft::DispensingSlot& f1) = 0;	// 購入
    virtual void update(ft::Deposit& f0) = 0;	// 状態の更新
};


//--------------------------------------
// Slots interface
// 商品一覧
//--------------------------------------
struct Slots {
    virtual ~Slots() = default;

    virtual bool can_buy(const ev::Buy& e, const ft::Deposit& f0) const = 0;	// 購入可能？
    virtual bool has_slot(const ev::Buy& e) const = 0;	// 商品ある？
    virtual void buy(const ev::Buy& e, ft::Deposit& f0, ft::DispensingSlot& f1) = 0;	// 購入
    virtual void update(ft::Deposit& f0) = 0;	// 状態の更新
};


//--------------------------------------
// SlotUI interface
//--------------------------------------
struct SlotUI {
    virtual ~SlotUI() = default;

    virtual void activate() = 0;	// 購入可能状態
    virtual void standby() = 0;	// 待機状態
    virtual void no_stock() = 0;	// 在庫切れ
    virtual void set_info(const ev::ProductInfo& e) = 0;	// 情報の設定
};

} // namespace ft

namespace stub {
//--------------------------------------
// Deposit stub
//--------------------------------------
struct Deposit: ft::Deposit {
    bool is_ready_ = false;
    bool has_deposit_ = false;
    int buy_ = 0;
    int refund_ = 0;
    int deposit_ = 0;

    bool is_ready(const ev::Deposit& e) const override {
        return is_ready_;
    }
    bool has_deposit(int money = 1) const override {
        return has_deposit_;
    }
    void buy(int price = 0) override {
        ++buy_;
    }
    void refund() override {
        ++refund_;
    }
    void deposit(const ev::Deposit& e) override {
        ++deposit_;
    }
};

//--------------------------------------
// DispensingSlot stub
//--------------------------------------
struct DispensingSlot: ft::DispensingSlot {
    int dispense_ = 0;

    void dispense(string_type name) override {
        ++dispense_;
    }
};

//--------------------------------------
// Slot stub
//--------------------------------------
struct Slot: ft::Slot {
    bool has_deposit_ = false;
    bool has_stock_ = false;
    int buy_ = 0;
    int update_ = 0;

    bool has_deposit(const ft::Deposit& f0) const override {
        return has_deposit_;
    }
    bool has_stock() const override {
        return has_stock_;
    }
    void buy(ft::Deposit& f0, ft::DispensingSlot& f1) override {
        ++buy_;
    }
    void update(ft::Deposit& f0) override {
        ++update_;
    }
};

//--------------------------------------
// Slots stub
//--------------------------------------
struct Slots: ft::Slots {
    bool can_buy_ = false;
    bool has_slot_ = false;
    int buy_ = 0;
    int update_ = 0;

    bool can_buy(const ev::Buy& e, const ft::Deposit& f0) const override {
        return can_buy_;
    }
    bool has_slot(const ev::Buy& e) const override {
        return has_slot_;
    }
    void buy(const ev::Buy& e, ft::Deposit& f0, ft::DispensingSlot& f1) override {
        ++buy_;
    }
    void update(ft::Deposit& f0) override {
        ++update_;
    }
};

//--------------------------------------
// SlotUI stub
//--------------------------------------
struct SlotUI: ft::SlotUI {
    int activate_ = 0;
    int standby_ = 0;
    int no_stock_ = 0;
    int set_info_ = 0;

    void activate() override {
        ++activate_;
    }
    void standby() override {
        ++standby_;
    }
    void no_stock() override {
        ++no_stock_;
    }
    void set_info(const ev::ProductInfo& e) override {
        ++set_info_;
    }
};

} // namespace stub

} // namespace vending_machine
} // namespace rokumoto
} // namespace app
