//------------------------------------------------------------------------------
//  vending_machine.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"
#include "features.h"

namespace app {
namespace rokumoto {
namespace vending_machine {
namespace sm {

struct VendingMachine {
    struct Check {};
    struct Ready {};
    struct Standby {};
    struct ft_Slots_CanBuy {
        bool operator()(const ft::Slots& o, const ev::Buy& e, const ft::Deposit& f0) const {
            return o.can_buy(e, f0);
        }
    };
    struct ft_Deposit_HasDeposit {
        int money = 1;
        bool operator()(const ft::Deposit& o) const {
            return o.has_deposit(money);
        }
    };
    struct ft_Deposit_IsReady {
        bool operator()(const ft::Deposit& o, const ev::Deposit& e) const {
            return o.is_ready(e);
        }
    };

    struct ft_Slots_Buy {
        void operator()(ft::Slots& o, const ev::Buy& e, ft::Deposit& f0, ft::DispensingSlot& f1) const {
            o.buy(e, f0, f1);
        }
    };
    struct ft_Deposit_Deposit {
        void operator()(ft::Deposit& o, const ev::Deposit& e) const {
            o.deposit(e);
        }
    };
    struct ft_Deposit_Refund {
        void operator()(ft::Deposit& o) const {
            o.refund();
        }
    };
    struct ft_StateLog_SetState {
        string_type state;
        void operator()(ft::StateLog& o) const {
            o.set_state(state);
        }
    };
    struct ft_Slots_Update {
        void operator()(ft::Slots& o, ft::Deposit& f0) const {
            o.update(f0);
        }
    };

    auto operator()() const {
        using namespace boost::sml;
        return make_transition_table(
            *state<Standby> + on_entry<_> / (ft_StateLog_SetState{ "準備中" },ft_Slots_Update{  })
            ,state<Standby> + event<ev::Deposit>[ft_Deposit_IsReady{  }] / ft_Deposit_Deposit{  } = state<Ready>
            ,state<Ready> + on_entry<_> / (ft_StateLog_SetState{ "購入待ち" },ft_Slots_Update{  })
            ,state<Ready> + event<ev::Deposit> / (ft_Deposit_Deposit{  },ft_Slots_Update{  })
            ,state<Ready> + event<ev::Refund> / ft_Deposit_Refund{  } = state<Standby>
            ,state<Ready> + event<ev::Buy>[ft_Slots_CanBuy{  }] / ft_Slots_Buy{  } = state<Check>
            ,state<Check> + on_entry<_> / ft_Slots_Update{  }
            ,state<Check>[!ft_Deposit_HasDeposit{  }] = state<Standby>
            ,state<Check> = state<Ready>
        );
    }
};
} // namespace sm

struct VendingMachine: sml::sm<sm::VendingMachine> {
    using sm_t = app::rokumoto::vending_machine::sm::VendingMachine;
    using this_type = VendingMachine;
    using base_type = sml::sm<sm_t>;

    VendingMachine(ft::Deposit& f0 ,ft::Slots& f1 ,ft::DispensingSlot& f2 ,ft::StateLog& f3)
        : base_type{f0 ,f1 ,f2 ,f3}
    {
    }
};
} // namespace vending_machine
} // namespace rokumoto
} // namespace app
