//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace prj_abc {
namespace ev {

// イベントA
struct AAA {
    int count;	// カウント

};


struct BBB {};


struct CCC {};

} // namespace ev
} // namespace prj_abc
} // namespace app
