//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace prj_abc {
namespace ft {
struct feature_abc;

//--------------------------------------
// feature_abc interface
//--------------------------------------
struct feature_abc {
    virtual ~feature_abc() = default;

    virtual bool check_count(const ev::AAA& e, int value = 0) const = 0;
    virtual void set_message(string_type message) = 0;	// メッセージ
};

} // namespace ft

namespace stub {
//--------------------------------------
// feature_abc stub
//--------------------------------------
struct feature_abc: ft::feature_abc {
    bool check_count_ = false;
    int set_message_ = 0;

    bool check_count(const ev::AAA& e, int value = 0) const override {
        return check_count_;
    }
    void set_message(string_type message) override {
        ++set_message_;
    }
};

} // namespace stub

} // namespace prj_abc
} // namespace app
