//------------------------------------------------------------------------------
//  state_abc.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"
#include "features.h"

namespace app {
namespace prj_abc {
namespace sm {

struct state_abc {
    struct AAA {};
    struct BBB {};
    struct CCC {};
    struct ft_feature_abc_CheckCount {
        int value = 0;
        bool operator()(const ft::feature_abc& o, const ev::AAA& e) const {
            return o.check_count(e, value);
        }
    };

    struct ft_feature_abc_SetMessage {
        string_type message;
        void operator()(ft::feature_abc& o) const {
            o.set_message(message);
        }
    };

    auto operator()() const {
        using namespace boost::sml;
        return make_transition_table(
            *state<AAA> + event<ev::BBB> / ft_feature_abc_SetMessage{  } = state<BBB>
            ,state<BBB> + event<ev::CCC> / ft_feature_abc_SetMessage{  } = state<CCC>
            ,state<CCC> + event<ev::AAA>[ft_feature_abc_CheckCount{ 0 }] / ft_feature_abc_SetMessage{  } = state<AAA>
        );
    }
};
} // namespace sm

struct state_abc: sml::sm<sm::state_abc> {
    using sm_t = app::prj_abc::sm::state_abc;
    using this_type = state_abc;
    using base_type = sml::sm<sm_t>;

    state_abc(ft::feature_abc& f0)
        : base_type{f0}
    {
    }
};
} // namespace prj_abc
} // namespace app
