//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace prj_hp {
namespace ev {

// 表示
struct show {
    bool isSkip;	// 演出スキップするか
    float maxHp;	// Hp上限
    float currentHp;

};


// 非表示
struct hide {
    bool isSkip;

};


struct onAppeared {};	// 表示演出終了


struct onDisappeared {};	// 非表示演出終了


// 追加
struct addHp {
    float value;

};


// 減少
struct subHp {
    float value;

};

} // namespace ev
} // namespace prj_hp
} // namespace app
