//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace prj_hp {
namespace ft {
struct feature_hp;

//--------------------------------------
// feature_hp interface
//--------------------------------------
struct feature_hp {
    virtual ~feature_hp() = default;

    virtual bool is_show_skip(const ev::show& e) const = 0;	// 表示演出スキップ
    virtual bool is_hide_skip(const ev::hide& e) const = 0;	// 非表示演出スキップ
    virtual void show(const ev::show& e) = 0;	// 表示
    virtual void hide(const ev::hide& e) = 0;	// 非表示
    virtual void add_hp(const ev::addHp& e) = 0;	// HPが追加
    virtual void sub_hp(const ev::subHp& e) = 0;	// HPが減少
};

} // namespace ft

namespace stub {
//--------------------------------------
// feature_hp stub
//--------------------------------------
struct feature_hp: ft::feature_hp {
    bool is_show_skip_ = false;
    bool is_hide_skip_ = false;
    int show_ = 0;
    int hide_ = 0;
    int add_hp_ = 0;
    int sub_hp_ = 0;

    bool is_show_skip(const ev::show& e) const override {
        return is_show_skip_;
    }
    bool is_hide_skip(const ev::hide& e) const override {
        return is_hide_skip_;
    }
    void show(const ev::show& e) override {
        ++show_;
    }
    void hide(const ev::hide& e) override {
        ++hide_;
    }
    void add_hp(const ev::addHp& e) override {
        ++add_hp_;
    }
    void sub_hp(const ev::subHp& e) override {
        ++sub_hp_;
    }
};

} // namespace stub

} // namespace prj_hp
} // namespace app
