//------------------------------------------------------------------------------
//  state_hp.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"
#include "features.h"

namespace app {
namespace prj_hp {
namespace sm {

struct state_hp {
    struct Appearing {};
    struct Disappearing {};
    struct Hide {};
    struct Show {};
    struct ft_feature_hp_IsHideSkip {
        bool operator()(const ft::feature_hp& o, const ev::hide& e) const {
            return o.is_hide_skip(e);
        }
    };
    struct ft_feature_hp_IsShowSkip {
        bool operator()(const ft::feature_hp& o, const ev::show& e) const {
            return o.is_show_skip(e);
        }
    };

    struct ft_feature_hp_AddHp {
        void operator()(ft::feature_hp& o, const ev::addHp& e) const {
            o.add_hp(e);
        }
    };
    struct ft_feature_hp_Hide {
        void operator()(ft::feature_hp& o, const ev::hide& e) const {
            o.hide(e);
        }
    };
    struct ft_feature_hp_Show {
        void operator()(ft::feature_hp& o, const ev::show& e) const {
            o.show(e);
        }
    };
    struct ft_feature_hp_SubHp {
        void operator()(ft::feature_hp& o, const ev::subHp& e) const {
            o.sub_hp(e);
        }
    };

    auto operator()() const {
        using namespace boost::sml;
        return make_transition_table(
            state<Show> + event<ev::addHp> / ft_feature_hp_AddHp{  }
            ,state<Show> + event<ev::subHp> / ft_feature_hp_SubHp{  }
            ,*state<Hide> + event<ev::show>[ft_feature_hp_IsShowSkip{  }] / ft_feature_hp_Show{  } = state<Show>
            ,state<Hide> + event<ev::show> / ft_feature_hp_Show{  } = state<Appearing>
            ,state<Disappearing> + event<ev::show>[ft_feature_hp_IsShowSkip{  }] / ft_feature_hp_Show{  } = state<Show>
            ,state<Disappearing> + event<ev::show> / ft_feature_hp_Show{  } = state<Appearing>
            ,state<Disappearing> + event<ev::onDisappeared> = state<Hide>
            ,state<Show> + event<ev::hide>[ft_feature_hp_IsHideSkip{  }] / ft_feature_hp_Hide{  } = state<Hide>
            ,state<Show> + event<ev::hide> / ft_feature_hp_Hide{  } = state<Disappearing>
            ,state<Appearing> + event<ev::hide>[ft_feature_hp_IsHideSkip{  }] / ft_feature_hp_Hide{  } = state<Hide>
            ,state<Appearing> + event<ev::hide> / ft_feature_hp_Hide{  } = state<Disappearing>
            ,state<Appearing> + event<ev::onAppeared> = state<Show>
            ,state<Appearing> + event<ev::addHp> / ft_feature_hp_AddHp{  }
            ,state<Appearing> + event<ev::subHp> / ft_feature_hp_SubHp{  }
        );
    }
};
} // namespace sm

struct state_hp: sml::sm<sm::state_hp> {
    using sm_t = app::prj_hp::sm::state_hp;
    using this_type = state_hp;
    using base_type = sml::sm<sm_t>;

    state_hp(ft::feature_hp& f0)
        : base_type{f0}
    {
    }
};
} // namespace prj_hp
} // namespace app
