//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace shop {
namespace ev {

struct Show {};	// 表示


// 商品カーソル移動
struct SelectItem {
    int item_num;	// 商品番号

};


// 購入個数変更
struct ChangeQuantity {
    int quantity;	// 個数（+1または-1）

};


struct Decide {};	// 決定


struct Cancel {};	// 戻る/非表示

} // namespace ev
} // namespace shop
} // namespace app
