//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace shop {
namespace ft {
struct Funds;
struct Item;
struct Selection;
struct ItemList;
struct Shop_UI;
struct Item_UI;

//--------------------------------------
// Funds interface
// 所持金管理
//--------------------------------------
struct Funds {
    virtual ~Funds() = default;

    virtual bool has_funds(int money) const = 0;	// 受け取った金額が所持金以下か
    virtual void spend(int money) = 0;	// 購入処理（所持金ーmoney）
};


//--------------------------------------
// Item interface
// ショップの商品
//--------------------------------------
struct Item {
    virtual ~Item() = default;

    virtual bool has_funds(const ft::Funds& f0, int num = 1) const = 0;	// 所持金管理の所持金チェック呼び出し
    virtual bool has_stock(int num = 1) const = 0;	// 在庫チェック
    virtual void change_quantity(const ev::ChangeQuantity& e, ft::Funds& f0, ft::Selection& f1) = 0;	// 個数管理の個数変更処理呼び出し
    virtual void purchase(ft::Funds& f0, int num = 1) = 0;	// 所持金管理の購入処理呼び出し
    virtual void update(ft::Funds& f0, int num = 1, bool isFocused = false, bool isSelected = false) = 0;	// 状態更新処理
};


//--------------------------------------
// Selection interface
// 商品の選択個数管理
//--------------------------------------
struct Selection {
    virtual ~Selection() = default;

    virtual bool has_funds(const ft::Item& f0, const ft::Funds& f1) const = 0;	// 商品の所持金チェック呼び出し
    virtual bool has_stock(const ft::Item& f0) const = 0;	// 商品の在庫あるかチェック呼び出し
    virtual void change_quantity(int quantity = 1, int buyable_num = 1) = 0;	// 個数変更処理
    virtual void purchase(ft::Item& f0, ft::Funds& f1) = 0;	// 商品の購入処理呼び出し
    virtual void update(ft::Item& f0, ft::Funds& f1, bool isFocused = false, bool isSelected = false) = 0;	// 商品の状態更新呼び出し
    virtual void reset() = 0;	// 個数リセット
};


//--------------------------------------
// ItemList interface
// ショップの商品リスト/選択中の商品に対する操作
//--------------------------------------
struct ItemList {
    virtual ~ItemList() = default;

    virtual bool can_buy(const ft::Selection& f0, const ft::Funds& f1) const = 0;	// 個数管理の所持金チェック呼び出し
    virtual bool has_stock(const ft::Selection& f0) const = 0;	// 個数管理の指定商品の在庫あるかチェック呼び出し
    virtual void change_quantity(const ev::ChangeQuantity& e, ft::Selection& f0, ft::Funds& f1) = 0;	// 指定商品の個数変更処理呼び出し
    virtual void purchase(ft::Selection& f0, ft::Funds& f1) = 0;	// 個数管理の購入処理呼び出し（指定商品のみ）
    virtual void update(ft::Selection& f0, ft::Funds& f1) = 0;	// 個数管理の状態更新処理呼び出し（全商品分）
    virtual void focus(const ev::SelectItem& e) = 0;	// 指定番号商品にカーソルをあわせる
    virtual void set_selecting(bool isSelecting = false) = 0;	// カーソルを合わせている商品を選択状況の設定
};


//--------------------------------------
// Shop_UI interface
// ショップ画面UI
//--------------------------------------
struct Shop_UI {
    virtual ~Shop_UI() = default;

    virtual void show() = 0;	// 表示
    virtual void hide() = 0;	// 非表示
};


//--------------------------------------
// Item_UI interface
// 商品UI
//--------------------------------------
struct Item_UI {
    virtual ~Item_UI() = default;

    virtual void locked() = 0;	// 待機/購入不可
    virtual void normal() = 0;	// 待機/購入可
    virtual void focus() = 0;	// カーソルがあっている
    virtual void quantityselect() = 0;	// 個数選択中
    virtual void soldout() = 0;	// 品切れ
};

} // namespace ft

namespace stub {
//--------------------------------------
// Funds stub
//--------------------------------------
struct Funds: ft::Funds {
    bool has_funds_ = false;
    int spend_ = 0;

    bool has_funds(int money) const override {
        return has_funds_;
    }
    void spend(int money) override {
        ++spend_;
    }
};

//--------------------------------------
// Item stub
//--------------------------------------
struct Item: ft::Item {
    bool has_funds_ = false;
    bool has_stock_ = false;
    int change_quantity_ = 0;
    int purchase_ = 0;
    int update_ = 0;

    bool has_funds(const ft::Funds& f0, int num = 1) const override {
        return has_funds_;
    }
    bool has_stock(int num = 1) const override {
        return has_stock_;
    }
    void change_quantity(const ev::ChangeQuantity& e, ft::Funds& f0, ft::Selection& f1) override {
        ++change_quantity_;
    }
    void purchase(ft::Funds& f0, int num = 1) override {
        ++purchase_;
    }
    void update(ft::Funds& f0, int num = 1, bool isFocused = false, bool isSelected = false) override {
        ++update_;
    }
};

//--------------------------------------
// Selection stub
//--------------------------------------
struct Selection: ft::Selection {
    bool has_funds_ = false;
    bool has_stock_ = false;
    int change_quantity_ = 0;
    int purchase_ = 0;
    int update_ = 0;
    int reset_ = 0;

    bool has_funds(const ft::Item& f0, const ft::Funds& f1) const override {
        return has_funds_;
    }
    bool has_stock(const ft::Item& f0) const override {
        return has_stock_;
    }
    void change_quantity(int quantity = 1, int buyable_num = 1) override {
        ++change_quantity_;
    }
    void purchase(ft::Item& f0, ft::Funds& f1) override {
        ++purchase_;
    }
    void update(ft::Item& f0, ft::Funds& f1, bool isFocused = false, bool isSelected = false) override {
        ++update_;
    }
    void reset() override {
        ++reset_;
    }
};

//--------------------------------------
// ItemList stub
//--------------------------------------
struct ItemList: ft::ItemList {
    bool can_buy_ = false;
    bool has_stock_ = false;
    int change_quantity_ = 0;
    int purchase_ = 0;
    int update_ = 0;
    int focus_ = 0;
    int set_selecting_ = 0;

    bool can_buy(const ft::Selection& f0, const ft::Funds& f1) const override {
        return can_buy_;
    }
    bool has_stock(const ft::Selection& f0) const override {
        return has_stock_;
    }
    void change_quantity(const ev::ChangeQuantity& e, ft::Selection& f0, ft::Funds& f1) override {
        ++change_quantity_;
    }
    void purchase(ft::Selection& f0, ft::Funds& f1) override {
        ++purchase_;
    }
    void update(ft::Selection& f0, ft::Funds& f1) override {
        ++update_;
    }
    void focus(const ev::SelectItem& e) override {
        ++focus_;
    }
    void set_selecting(bool isSelecting = false) override {
        ++set_selecting_;
    }
};

//--------------------------------------
// Shop_UI stub
//--------------------------------------
struct Shop_UI: ft::Shop_UI {
    int show_ = 0;
    int hide_ = 0;

    void show() override {
        ++show_;
    }
    void hide() override {
        ++hide_;
    }
};

//--------------------------------------
// Item_UI stub
//--------------------------------------
struct Item_UI: ft::Item_UI {
    int locked_ = 0;
    int normal_ = 0;
    int focus_ = 0;
    int quantityselect_ = 0;
    int soldout_ = 0;

    void locked() override {
        ++locked_;
    }
    void normal() override {
        ++normal_;
    }
    void focus() override {
        ++focus_;
    }
    void quantityselect() override {
        ++quantityselect_;
    }
    void soldout() override {
        ++soldout_;
    }
};

} // namespace stub

} // namespace shop
} // namespace app
