//------------------------------------------------------------------------------
//  state_ui_visibility.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"
#include "features.h"

namespace app {
namespace shop {
namespace sm {

struct state_ui_visibility {
    struct Hide {};

    struct ft_Shop_UI_Hide {
        void operator()(ft::Shop_UI& o) const {
            o.hide();
        }
    };
    struct ft_Shop_UI_Show {
        void operator()(ft::Shop_UI& o) const {
            o.show();
        }
    };

    auto operator()() const {
        using namespace boost::sml;
        return make_transition_table(
            *state<Hide> + event<ev::Show> / ft_Shop_UI_Show{  } = state<sm::state_shop>
            ,state<sm::state_shop> + event<ev::Cancel> / ft_Shop_UI_Hide{  } = state<Hide>
        );
    }
};
} // namespace sm

struct state_ui_visibility: sml::sm<sm::state_ui_visibility> {
    using sm_t = app::shop::sm::state_ui_visibility;
    using this_type = state_ui_visibility;
    using base_type = sml::sm<sm_t>;

    state_ui_visibility(ft::Funds& f0 ,ft::Selection& f1 ,ft::ItemList& f2 ,ft::Item& f3 ,ft::Shop_UI& f4 ,ft::Item_UI& f5)
        : base_type{f0 ,f1 ,f2 ,f3 ,f4 ,f5}
    {
    }
};
} // namespace shop
} // namespace app
