//------------------------------------------------------------------------------
//  state_shop.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"
#include "features.h"

namespace app {
namespace shop {
namespace sm {

struct state_shop {
    struct Idle {};
    struct Selecting {};
    struct ft_ItemList_CanBuy {
        bool operator()(const ft::ItemList& o, const ft::Selection& f0, const ft::Funds& f1) const {
            return o.can_buy(f0, f1);
        }
    };
    struct ft_Item_HasStock {
        int num = 1;
        bool operator()(const ft::Item& o) const {
            return o.has_stock(num);
        }
    };

    struct ft_ItemList_ChangeQuantity {
        void operator()(ft::ItemList& o, const ev::ChangeQuantity& e, ft::Selection& f0, ft::Funds& f1) const {
            o.change_quantity(e, f0, f1);
        }
    };
    struct ft_ItemList_Focus {
        void operator()(ft::ItemList& o, const ev::SelectItem& e) const {
            o.focus(e);
        }
    };
    struct ft_ItemList_Purchase {
        void operator()(ft::ItemList& o, ft::Selection& f0, ft::Funds& f1) const {
            o.purchase(f0, f1);
        }
    };
    struct ft_Selection_Reset {
        void operator()(ft::Selection& o) const {
            o.reset();
        }
    };
    struct ft_ItemList_SetSelecting {
        bool isSelecting = false;
        void operator()(ft::ItemList& o) const {
            o.set_selecting(isSelecting);
        }
    };
    struct ft_ItemList_Update {
        void operator()(ft::ItemList& o, ft::Selection& f0, ft::Funds& f1) const {
            o.update(f0, f1);
        }
    };

    auto operator()() const {
        using namespace boost::sml;
        return make_transition_table(
            *state<Idle> + on_entry<_> / (ft_Selection_Reset{  },ft_ItemList_Update{  })
            ,state<Idle> + event<ev::SelectItem> / (ft_ItemList_Focus{  },ft_ItemList_Update{  })
            ,state<Idle> + event<ev::Decide>[ft_Item_HasStock{  }] / ft_ItemList_SetSelecting{ true } = state<Selecting>
            ,state<Selecting> + on_entry<_> / ft_ItemList_Update{  }
            ,state<Selecting> + event<ev::ChangeQuantity> / (ft_ItemList_ChangeQuantity{  },ft_ItemList_Update{  })
            ,state<Selecting> + event<ev::Decide>[ft_ItemList_CanBuy{  }] / (ft_ItemList_Purchase{  },ft_ItemList_SetSelecting{ false }) = state<Idle>
            ,state<Selecting> + event<ev::Cancel> / (ft_ItemList_SetSelecting{ false },ft_ItemList_Update{  }) = state<Idle>
        );
    }
};
} // namespace sm

struct state_shop: sml::sm<sm::state_shop> {
    using sm_t = app::shop::sm::state_shop;
    using this_type = state_shop;
    using base_type = sml::sm<sm_t>;

    state_shop(ft::Funds& f0 ,ft::Selection& f1 ,ft::ItemList& f2 ,ft::Item& f3 ,ft::Shop_UI& f4 ,ft::Item_UI& f5)
        : base_type{f0 ,f1 ,f2 ,f3 ,f4 ,f5}
    {
    }
};
} // namespace shop
} // namespace app
