//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace hp_bar {
namespace ev {

// HPの設定
struct Hp {
    int hp;	// 設定するHPの量

};


// ダメージを受ける
struct Damage {
    int hp;	// 受けたダメージ量

};


// 回復
struct Heal {
    int hp;	// 回復量

};

} // namespace ev
} // namespace hp_bar
} // namespace app
