//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace hp_bar {
namespace ev {
} // namespace ev
} // namespace hp_bar
} // namespace app
