//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace hp_bar {
namespace ft {
using StateLog = app::StateLog;
} // namespace ft

namespace stub {
} // namespace stub

} // namespace hp_bar
} // namespace app
