//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace hp_bar {
namespace ft {
struct HpBar;

//--------------------------------------
// HpBar interface
//--------------------------------------
struct HpBar {
    virtual ~HpBar() = default;

    virtual bool can_damage(const ev::Damage& e) const = 0;	// ダメージを受ける？
    virtual bool is_dead() const = 0;	// 死んでる？
    virtual bool is_max() const = 0;	// 体力満タン？
    virtual void set_hp(const ev::Hp& e) = 0;	// HPの設定
    virtual void damage(const ev::Damage& e) = 0;	// ダメージを受ける
    virtual void heal(const ev::Heal& e) = 0;	// 回復する
};

} // namespace ft

namespace stub {
//--------------------------------------
// HpBar stub
//--------------------------------------
struct HpBar: ft::HpBar {
    bool can_damage_ = false;
    bool is_dead_ = false;
    bool is_max_ = false;
    int set_hp_ = 0;
    int damage_ = 0;
    int heal_ = 0;

    bool can_damage(const ev::Damage& e) const override {
        return can_damage_;
    }
    bool is_dead() const override {
        return is_dead_;
    }
    bool is_max() const override {
        return is_max_;
    }
    void set_hp(const ev::Hp& e) override {
        ++set_hp_;
    }
    void damage(const ev::Damage& e) override {
        ++damage_;
    }
    void heal(const ev::Heal& e) override {
        ++heal_;
    }
};

} // namespace stub

} // namespace hp_bar
} // namespace app
