//------------------------------------------------------------------------------
//  hp_bar_executor.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"
#include "features.h"

namespace app {
namespace hp_bar {
namespace sm {
using namespace smx;

template <class E> struct event_traits;
template <> struct event_traits<ev::Hp> { static constexpr hash_type hash = name_hash("ev::Hp"); };
template <> struct event_traits<ev::Damage> { static constexpr hash_type hash = name_hash("ev::Damage"); };
template <> struct event_traits<ev::Heal> { static constexpr hash_type hash = name_hash("ev::Heal"); };

struct Executor: ExecutorBase<Executor> {
    template <class E>
    static constexpr hash_type event_hash() { return event_traits<E>::hash; }
    std::tuple<ft::HpBar&,ft::StateLog&> feats;

    Executor(ft::HpBar& f0 ,ft::StateLog& f1)
        : feats{f0 ,f1}
    {
    }

    bool startup(const buffer_type& bin)
    {
        Node node;
        if (!compile_machine(node, from_binary(bin), feats))
            return false;
        roots.push_back(std::move(node));
        return start();
    }
    struct ft_HpBar_CanDamage {
        template <class F>
        bound_guard_type operator()(F& fx, BinReader& args) const
        {
            auto* m = &std::get<ft::HpBar&>(fx);
            return [m](const void* e) { m->can_damage(*static_cast<const ev::Damage*>(e)); };
        }
    };
    struct ft_HpBar_IsDead {
        template <class F>
        bound_guard_type operator()(F& fx, BinReader& args) const
        {
            auto* m = &std::get<ft::HpBar&>(fx);
            return [m](const void* e) { m->is_dead(); };
        }
    };
    struct ft_HpBar_IsMax {
        template <class F>
        bound_guard_type operator()(F& fx, BinReader& args) const
        {
            auto* m = &std::get<ft::HpBar&>(fx);
            return [m](const void* e) { m->is_max(); };
        }
    };

    struct ft_HpBar_Damage {
        template <class F>
        bound_action_type operator()(F& fx, BinReader& args) const
        {
            auto* m = &std::get<ft::HpBar&>(fx);
            return [m](const void* e) { m->damage(*static_cast<const ev::Damage*>(e)); };
        }
    };
    struct ft_HpBar_Heal {
        template <class F>
        bound_action_type operator()(F& fx, BinReader& args) const
        {
            auto* m = &std::get<ft::HpBar&>(fx);
            return [m](const void* e) { m->heal(*static_cast<const ev::Heal*>(e)); };
        }
    };
    struct ft_HpBar_SetHp {
        template <class F>
        bound_action_type operator()(F& fx, BinReader& args) const
        {
            auto* m = &std::get<ft::HpBar&>(fx);
            return [m](const void* e) { m->set_hp(*static_cast<const ev::Hp*>(e)); };
        }
    };
    struct ft_StateLog_SetState {
        template <class F>
        bound_action_type operator()(F& fx, BinReader& args) const
        {
            auto* m = &std::get<ft::StateLog&>(fx);
            auto state = args.read<string_type>();
            return [m, state](const void* e) { m->set_state(state); };
        }
    };

    template <class F>
    static std::optional<bound_action_type> bind_action(hash_type hash, F& fx, BinReader& args)
    {
        switch (hash) {
        case name_hash("ft_HpBar_Damage"):
            return ft_HpBar_Damage{}(fx, args);
        case name_hash("ft_HpBar_Heal"):
            return ft_HpBar_Heal{}(fx, args);
        case name_hash("ft_HpBar_SetHp"):
            return ft_HpBar_SetHp{}(fx, args);
        case name_hash("ft_StateLog_SetState"):
            return ft_StateLog_SetState{}(fx, args);
        }
        return std::nullopt;
    }

    template <class F>
    static std::optional<bound_guard_type> bind_guard(hash_type hash, F& fx, BinReader& args)
    {
        switch (hash) {
        case name_hash("ft_HpBar_CanDamage"):
            return ft_HpBar_CanDamage{}(fx, args);
        case name_hash("ft_HpBar_IsDead"):
            return ft_HpBar_IsDead{}(fx, args);
        case name_hash("ft_HpBar_IsMax"):
            return ft_HpBar_IsMax{}(fx, args);
        }
        return std::nullopt;
    }
};

} // namespace sm
} // namespace hp_bar
} // namespace app
