//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace prj_vendingmachine {
namespace ev {

// 入金
struct SetMoney {
    int addMoney;	// 入金するお金

};


// 飲み物ボタン押す
struct PushDrinkbutton {
    int buttonNum;	// ボタン番号

};


struct PushReturnbutton {};	// おつりボタン押す

} // namespace ev
} // namespace prj_vendingmachine
} // namespace app
