//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace prj_vendingmachine {
namespace ft {
struct feature_vendingmachine;

//--------------------------------------
// feature_vendingmachine interface
//--------------------------------------
struct feature_vendingmachine {
    virtual ~feature_vendingmachine() = default;

    virtual bool isPurchasable(const ev::PushDrinkbutton& e) const = 0;	// 購入可能か
    virtual void add_money(const ev::SetMoney& e) = 0;	// 入金されたお金を追加
    virtual void update_button_status() = 0;	// 飲み物ボタンのステータス更新
    virtual void buy() = 0;	// 購入
    virtual void refund() = 0;	// 返金
};

} // namespace ft

namespace stub {
//--------------------------------------
// feature_vendingmachine stub
//--------------------------------------
struct feature_vendingmachine: ft::feature_vendingmachine {
    bool isPurchasable_ = false;
    int add_money_ = 0;
    int update_button_status_ = 0;
    int buy_ = 0;
    int refund_ = 0;

    bool isPurchasable(const ev::PushDrinkbutton& e) const override {
        return isPurchasable_;
    }
    void add_money(const ev::SetMoney& e) override {
        ++add_money_;
    }
    void update_button_status() override {
        ++update_button_status_;
    }
    void buy() override {
        ++buy_;
    }
    void refund() override {
        ++refund_;
    }
};

} // namespace stub

} // namespace prj_vendingmachine
} // namespace app
