//------------------------------------------------------------------------------
//  state_vendingmachine.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"
#include "features.h"

namespace app {
namespace prj_vendingmachine {
namespace sm {

struct state_vendingmachine {
    struct CoinInserted {};
    struct Idle {};
    struct ft_feature_vendingmachine_IsPurchasable {
        bool operator()(const ft::feature_vendingmachine& o, const ev::PushDrinkbutton& e) const {
            return o.isPurchasable(e);
        }
    };

    struct ft_feature_vendingmachine_AddMoney {
        void operator()(ft::feature_vendingmachine& o, const ev::SetMoney& e) const {
            o.add_money(e);
        }
    };
    struct ft_feature_vendingmachine_Buy {
        void operator()(ft::feature_vendingmachine& o) const {
            o.buy();
        }
    };
    struct ft_feature_vendingmachine_Refund {
        void operator()(ft::feature_vendingmachine& o) const {
            o.refund();
        }
    };
    struct ft_feature_vendingmachine_UpdateButtonStatus {
        void operator()(ft::feature_vendingmachine& o) const {
            o.update_button_status();
        }
    };

    auto operator()() const {
        using namespace boost::sml;
        return make_transition_table(
            *state<Idle> + event<ev::SetMoney> / (ft_feature_vendingmachine_AddMoney{  },ft_feature_vendingmachine_UpdateButtonStatus{  }) = state<CoinInserted>
            ,state<CoinInserted> + event<ev::SetMoney> / (ft_feature_vendingmachine_AddMoney{  },ft_feature_vendingmachine_UpdateButtonStatus{  }) = state<CoinInserted>
            ,state<CoinInserted> + event<ev::PushDrinkbutton>[ft_feature_vendingmachine_IsPurchasable{  }] / ft_feature_vendingmachine_Buy{  } = state<Idle>
            ,state<CoinInserted> + event<ev::PushReturnbutton> / ft_feature_vendingmachine_Refund{  } = state<Idle>
        );
    }
};
} // namespace sm

struct state_vendingmachine: sml::sm<sm::state_vendingmachine> {
    using sm_t = app::prj_vendingmachine::sm::state_vendingmachine;
    using this_type = state_vendingmachine;
    using base_type = sml::sm<sm_t>;

    state_vendingmachine(ft::feature_vendingmachine& f0)
        : base_type{f0}
    {
    }
};
} // namespace prj_vendingmachine
} // namespace app
