//------------------------------------------------------------------------------
//  abc.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "../../smx_dynamic.h"
#include "events.h"
#include "features.h"

namespace app {
namespace aaa_prj {
namespace sm {
using namespace smx;

template <class E> struct event_traits;
template <> struct event_traits<ev::AAA> { static constexpr hash_type hash = name_hash("ev::AAA"); };
template <> struct event_traits<ev::BBB> { static constexpr hash_type hash = name_hash("ev::BBB"); };
template <> struct event_traits<ev::CCC> { static constexpr hash_type hash = name_hash("ev::CCC"); };

struct Executor: smx::ExecutorBase<Executor> {
    template <class E>
    static constexpr hash_type event_hash() { return event_traits<E>::hash; }
    std::tuple<ft::Output&> feats;

    Executor(ft::Output& f0)
        : feats{f0}
    {
    }

    bool startup(const buffer_type& bin)
    {
        Node node;
        if (!compile_machine(node, from_binary(bin), feats))
            return false;
        roots.push_back(std::move(node));
        return start();
    }

    struct ft_Output_SetLog {
        template <class F>
        bound_action_type operator()(F& fx, BinReader& args) const
        {
            auto* m = &std::get<ft::Output&>(fx);
            auto message = args.read<string_type>();
            return [m, message](const void* e) { m->set_log(message); };
        }
    };

    template <class F>
    static std::optional<bound_action_type> bind_action(hash_type hash, F& fx, BinReader& args)
    {
        switch (hash) {
        case name_hash("ft_Output_SetLog"):
            return ft_Output_SetLog{}(fx, args);
        }
        return std::nullopt;
    }

    template <class F>
    static std::optional<bound_guard_type> bind_guard(hash_type hash, F& fx, BinReader& args)
    {
        return std::nullopt;
    }
};

} // namespace sm
} // namespace aaa_prj
} // namespace app
