//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace aaa_prj {
namespace ev {

struct AAA {};


struct BBB {};


struct CCC {};

} // namespace ev
} // namespace aaa_prj
} // namespace app
