//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace aaa_prj {
namespace ft {
struct Output;

//--------------------------------------
// Output interface
//--------------------------------------
struct Output {
    virtual ~Output() = default;

    virtual bool has_log() const = 0;
    virtual void set_log(string_type message) = 0;
};

} // namespace ft

namespace stub {
//--------------------------------------
// Output stub
//--------------------------------------
struct Output: ft::Output {
    bool has_log_ = false;
    int set_log_ = 0;

    bool has_log() const override {
        return has_log_;
    }
    void set_log(string_type message) override {
        ++set_log_;
    }
};

} // namespace stub

} // namespace aaa_prj
} // namespace app
