//------------------------------------------------------------------------------
//  events.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"

namespace app {
namespace sample_prj {
namespace ev {
} // namespace ev
} // namespace sample_prj
} // namespace app
