//------------------------------------------------------------------------------
//  features.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"

namespace app {
namespace sample_prj {
namespace ft {
} // namespace ft

namespace stub {
} // namespace stub

} // namespace sample_prj
} // namespace app
