//------------------------------------------------------------------------------
//  sample1.h
//    generated from smx DO NOT EDIT THIS FILE
//------------------------------------------------------------------------------
#pragma once
#include "../configure.h"
#include "events.h"
#include "features.h"

namespace app {
namespace sample_prj {
namespace sm {

struct Sample1 {
    struct Bar {};
    struct Baz {};
    struct Foo {};

    struct ft_StateLog_SetState {
        string_type state;
        void operator()(ft::StateLog& o) const {
            o.set_state(state);
        }
    };

    auto operator()() const {
        using namespace boost::sml;
        return make_transition_table(
            *state<Foo> + on_entry<_> / ft_StateLog_SetState{ "Foo" }
            ,state<Bar> + on_entry<_> / ft_StateLog_SetState{ "Bar" }
            ,state<Baz> + on_entry<_> / ft_StateLog_SetState{ "Baz" }
            ,state<Foo> + event<ev::Bar> = state<Bar>
            ,state<Bar> + event<ev::Baz> = state<Baz>
            ,state<Baz> + event<ev::Foo> = state<Foo>
        );
    }
};
} // namespace sm

struct Sample1: sml::sm<sm::Sample1> {
    using sm_t = app::sample_prj::sm::Sample1;
    using this_type = Sample1;
    using base_type = sml::sm<sm_t>;

    Sample1(ft::StateLog& f0)
        : base_type{f0}
    {
    }
};
} // namespace sample_prj
} // namespace app
